### ISSUE TITLE
TypeError: '<=' not supported between instances of 'int' and 'str'  in File "data_process.py", line 31

### ISSUE THREAD

**Issue by OctoberGYY** [ytyz1307zzh/CMAC#1]
You mentioned *.img files are processed images by pretrained ResNet. But *img file I got consists of the image url. I dont't konw why cause this error. Is the toutiao_features.pkl file used for it?

**Comment by ytyz1307zzh** [comment]
Actually, the "data_process.py" file is just used to keep a backup script for myself... Can you explain what you want to do in detail?

**Comment by OctoberGYY** [comment]
I want to build my own dataset by running your code, but when I use the data_split function, it causes TypeError. I think there is something wrong with my *.img files.

**Comment by ytyz1307zzh** [comment]
Sorry for the inconvenience. Previously I just kept some backup files for myself (since this is not the official repo for this paper) so I did not expect other users may use these data processing files. I have reloaded some files into the data/ directory, and you might find data_selection.py and build_dataset.py useful. data_selection.py is used to select qualified data and you may change the conditions to your preference. build_dataset.py is used to combine image features and text data into new files.

**Comment by OctoberGYY** [comment]
It works! Thank you so much for your work and sharing.
